version: "3.9"
services:
  database:
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks: 
      - default
    ports:
    - "8080:8080"
volumes:
  data: